### ISSUE TITLE
huge number of collisions in timer handles

### ISSUE THREAD

**Issue by mscv** [wildstarnasa/GeminiTimer#1]
using tostring(timer) (line 233) to return timer handle results in collisions in as few as 2 timers.

makes using CancelTimer() virtually impossible (wrong/too many timers cancelled)

**Comment by Sinaloit** [comment]
tostring on a table should result in something similar to:

``` lua
table: 0x108cd0
```

the hex address is the memory address of the table, so there should be no collisions.  How have you verified this?

**Comment by mscv** [comment]
started logging handles in an indexed table. this is what i got: https://gist.github.com/mscv/0cd9cafb77d64c84800d

**Comment by Sinaloit** [comment]
Reuse of a specific table is expected.  Note:
https://github.com/wildstarnasa/GeminiTimer/blob/master/GeminiTimer-1.0.lua#L218-L219

the timerCache is stored when a single use or cancelled timer finishes so it can be reused:
https://github.com/wildstarnasa/GeminiTimer/blob/master/GeminiTimer-1.0.lua#L218-L219

if you add a cache stored entry I would expect that each duplicate you see is the stored timerCache which is just a reuse of an existing table (with new settings)

**Comment by mscv** [comment]
ok, that is it. i am generally storing a subset of handles for timers i create, then, at an arbitrary point in time do ClearTimer() with silent option on the set and recreate.

thanks for the help!

close please.

**Comment by Sinaloit** [comment]
Glad to help! Closing.
